//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMUPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int ID { get; set; }
        public string BillCode { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<int> GoodsID { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<double> Total { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
